package com.mithrilmania.blocktopograph.block;

import androidx.annotation.Nullable;

import com.mithrilmania.blocktopograph.block.blockproperty.BlockProperty;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public enum BlockType implements Serializable {
    AIR("minecraft:air", new BlockProperty[]{}),
    STONE("minecraft:stone", new BlockProperty[]{BlockProperty.STONE_TYPE}),
    GRASS("minecraft:grass", new BlockProperty[]{}),
    DIRT("minecraft:dirt", new BlockProperty[]{BlockProperty.DIRT_TYPE}),
    COBBLESTONE("minecraft:cobblestone", new BlockProperty[]{}),
    PLANKS("minecraft:planks", new BlockProperty[]{BlockProperty.WOOD_TYPE}),
    SAPLING("minecraft:sapling", new BlockProperty[]{BlockProperty.SAPLING_TYPE, BlockProperty.AGE_BIT}),
    BEDROCK("minecraft:bedrock", new BlockProperty[]{BlockProperty.INFINIBURN_BIT}),
    FLOWING_WATER("minecraft:flowing_water", new BlockProperty[]{BlockProperty.LIQUID_DEPTH}),
    WATER("minecraft:water", new BlockProperty[]{BlockProperty.LIQUID_DEPTH}),
    FLOWING_LAVA("minecraft:flowing_lava", new BlockProperty[]{BlockProperty.LIQUID_DEPTH}),
    LAVA("minecraft:lava", new BlockProperty[]{BlockProperty.LIQUID_DEPTH}),
    SAND("minecraft:sand", new BlockProperty[]{BlockProperty.SAND_TYPE}),
    GRAVEL("minecraft:gravel", new BlockProperty[]{}),
    GOLD_ORE("minecraft:gold_ore", new BlockProperty[]{}),
    IRON_ORE("minecraft:iron_ore", new BlockProperty[]{}),
    COAL_ORE("minecraft:coal_ore", new BlockProperty[]{}),
    LOG("minecraft:log", new BlockProperty[]{BlockProperty.OLD_LOG_TYPE, BlockProperty.PILLAR_AXIS}),
    LEAVES("minecraft:leaves", new BlockProperty[]{BlockProperty.OLD_LEAF_TYPE, BlockProperty.PERSISTENT_BIT, BlockProperty.UPDATE_BIT}),
    SPONGE("minecraft:sponge", new BlockProperty[]{BlockProperty.SPONGE_TYPE}),
    GLASS("minecraft:glass", new BlockProperty[]{}),
    LAPIS_ORE("minecraft:lapis_ore", new BlockProperty[]{}),
    LAPIS_BLOCK("minecraft:lapis_block", new BlockProperty[]{}),
    DISPENSER("minecraft:dispenser", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.TRIGGERED_BIT}),
    SANDSTONE("minecraft:sandstone", new BlockProperty[]{BlockProperty.SAND_STONE_TYPE}),
    NOTEBLOCK("minecraft:noteblock", new BlockProperty[]{}),
    BED("minecraft:bed", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.HEAD_PIECE_BIT, BlockProperty.OCCUPIED_BIT}),
    GOLDEN_RAIL("minecraft:golden_rail", new BlockProperty[]{BlockProperty.RAIL_DIRECTION, BlockProperty.RAIL_DATA_BIT}),
    DETECTOR_RAIL("minecraft:detector_rail", new BlockProperty[]{BlockProperty.RAIL_DIRECTION, BlockProperty.RAIL_DATA_BIT}),
    STICKY_PISTON("minecraft:sticky_piston", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    WEB("minecraft:web", new BlockProperty[]{}),
    TALLGRASS("minecraft:tallgrass", new BlockProperty[]{BlockProperty.TALL_GRASS_TYPE}),
    DEADBUSH("minecraft:deadbush", new BlockProperty[]{}),
    PISTON("minecraft:piston", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    PISTONARMCOLLISION("minecraft:pistonArmCollision", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    WOOL("minecraft:wool", new BlockProperty[]{BlockProperty.COLOR}),
    ELEMENT_0("minecraft:element_0", new BlockProperty[]{}),
    YELLOW_FLOWER("minecraft:yellow_flower", new BlockProperty[]{}),
    RED_FLOWER("minecraft:red_flower", new BlockProperty[]{BlockProperty.FLOWER_TYPE}),
    BROWN_MUSHROOM("minecraft:brown_mushroom", new BlockProperty[]{}),
    RED_MUSHROOM("minecraft:red_mushroom", new BlockProperty[]{}),
    GOLD_BLOCK("minecraft:gold_block", new BlockProperty[]{}),
    IRON_BLOCK("minecraft:iron_block", new BlockProperty[]{}),
    DOUBLE_STONE_SLAB("minecraft:double_stone_slab", new BlockProperty[]{BlockProperty.STONE_SLAB_TYPE, BlockProperty.TOP_SLOT_BIT}),
    STONE_SLAB("minecraft:stone_slab", new BlockProperty[]{BlockProperty.STONE_SLAB_TYPE, BlockProperty.TOP_SLOT_BIT}),
    BRICK_BLOCK("minecraft:brick_block", new BlockProperty[]{}),
    TNT("minecraft:tnt", new BlockProperty[]{BlockProperty.ALLOW_UNDERWATER_BIT, BlockProperty.EXPLODE_BIT}),
    BOOKSHELF("minecraft:bookshelf", new BlockProperty[]{}),
    MOSSY_COBBLESTONE("minecraft:mossy_cobblestone", new BlockProperty[]{}),
    OBSIDIAN("minecraft:obsidian", new BlockProperty[]{}),
    TORCH("minecraft:torch", new BlockProperty[]{BlockProperty.TORCH_FACING_DIRECTION}),
    FIRE("minecraft:fire", new BlockProperty[]{BlockProperty.AGE}),
    MOB_SPAWNER("minecraft:mob_spawner", new BlockProperty[]{}),
    OAK_STAIRS("minecraft:oak_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    CHEST("minecraft:chest", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    REDSTONE_WIRE("minecraft:redstone_wire", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    DIAMOND_ORE("minecraft:diamond_ore", new BlockProperty[]{}),
    DIAMOND_BLOCK("minecraft:diamond_block", new BlockProperty[]{}),
    CRAFTING_TABLE("minecraft:crafting_table", new BlockProperty[]{}),
    WHEAT("minecraft:wheat", new BlockProperty[]{BlockProperty.GROWTH}),
    FARMLAND("minecraft:farmland", new BlockProperty[]{BlockProperty.MOISTURIZED_AMOUNT}),
    FURNACE("minecraft:furnace", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    LIT_FURNACE("minecraft:lit_furnace", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    STANDING_SIGN("minecraft:standing_sign", new BlockProperty[]{BlockProperty.GROUND_SIGN_DIRECTION}),
    WOODEN_DOOR("minecraft:wooden_door", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.DOOR_HINGE_BIT, BlockProperty.OPEN_BIT, BlockProperty.UPPER_BLOCK_BIT}),
    LADDER("minecraft:ladder", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    RAIL("minecraft:rail", new BlockProperty[]{BlockProperty.RAIL_DIRECTION}),
    STONE_STAIRS("minecraft:stone_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    WALL_SIGN("minecraft:wall_sign", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    LEVER("minecraft:lever", new BlockProperty[]{BlockProperty.LEVER_DIRECTION, BlockProperty.OPEN_BIT}),
    STONE_PRESSURE_PLATE("minecraft:stone_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    IRON_DOOR("minecraft:iron_door", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.DOOR_HINGE_BIT, BlockProperty.OPEN_BIT, BlockProperty.UPPER_BLOCK_BIT}),
    WOODEN_PRESSURE_PLATE("minecraft:wooden_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    REDSTONE_ORE("minecraft:redstone_ore", new BlockProperty[]{}),
    LIT_REDSTONE_ORE("minecraft:lit_redstone_ore", new BlockProperty[]{}),
    UNLIT_REDSTONE_TORCH("minecraft:unlit_redstone_torch", new BlockProperty[]{}),
    REDSTONE_TORCH("minecraft:redstone_torch", new BlockProperty[]{BlockProperty.TORCH_FACING_DIRECTION}),
    STONE_BUTTON("minecraft:stone_button", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.BUTTON_PRESSED_BIT}),
    SNOW_LAYER("minecraft:snow_layer", new BlockProperty[]{BlockProperty.COVERED_BIT, BlockProperty.HEIGHT}),
    ICE("minecraft:ice", new BlockProperty[]{}),
    SNOW("minecraft:snow", new BlockProperty[]{}),
    CACTUS("minecraft:cactus", new BlockProperty[]{BlockProperty.AGE}),
    CLAY("minecraft:clay", new BlockProperty[]{}),
    REEDS("minecraft:reeds", new BlockProperty[]{BlockProperty.AGE}),
    JUKEBOX("minecraft:jukebox", new BlockProperty[]{}),
    FENCE("minecraft:fence", new BlockProperty[]{BlockProperty.WOOD_TYPE}),
    PUMPKIN("minecraft:pumpkin", new BlockProperty[]{BlockProperty.DIRECTION}),
    NETHERRACK("minecraft:netherrack", new BlockProperty[]{}),
    SOUL_SAND("minecraft:soul_sand", new BlockProperty[]{}),
    GLOWSTONE("minecraft:glowstone", new BlockProperty[]{}),
    PORTAL("minecraft:portal", new BlockProperty[]{BlockProperty.PORTAL_AXIS}),
    LIT_PUMPKIN("minecraft:lit_pumpkin", new BlockProperty[]{BlockProperty.DIRECTION}),
    CAKE("minecraft:cake", new BlockProperty[]{BlockProperty.BITE_COUNTER}),
    UNPOWERED_REPEATER("minecraft:unpowered_repeater", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.REPEATER_DELAY}),
    POWERED_REPEATER("minecraft:powered_repeater", new BlockProperty[]{}),
    INVISIBLEBEDROCK("minecraft:invisibleBedrock", new BlockProperty[]{}),
    TRAPDOOR("minecraft:trapdoor", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OPEN_BIT, BlockProperty.UPSIDE_DOWN_BIT}),
    MONSTER_EGG("minecraft:monster_egg", new BlockProperty[]{BlockProperty.MONSTER_EGG_STONE_TYPE}),
    STONEBRICK("minecraft:stonebrick", new BlockProperty[]{BlockProperty.STONE_BRICK_TYPE}),
    BROWN_MUSHROOM_BLOCK("minecraft:brown_mushroom_block", new BlockProperty[]{BlockProperty.HUGE_MUSHROOM_BITS}),
    RED_MUSHROOM_BLOCK("minecraft:red_mushroom_block", new BlockProperty[]{BlockProperty.HUGE_MUSHROOM_BITS}),
    IRON_BARS("minecraft:iron_bars", new BlockProperty[]{}),
    GLASS_PANE("minecraft:glass_pane", new BlockProperty[]{}),
    MELON_BLOCK("minecraft:melon_block", new BlockProperty[]{}),
    PUMPKIN_STEM("minecraft:pumpkin_stem", new BlockProperty[]{BlockProperty.GROWTH}),
    MELON_STEM("minecraft:melon_stem", new BlockProperty[]{BlockProperty.GROWTH}),
    VINE("minecraft:vine", new BlockProperty[]{BlockProperty.VINE_DIRECTION_BITS}),
    FENCE_GATE("minecraft:fence_gate", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.IN_WALL_BIT, BlockProperty.OPEN_BIT}),
    BRICK_STAIRS("minecraft:brick_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    STONE_BRICK_STAIRS("minecraft:stone_brick_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    MYCELIUM("minecraft:mycelium", new BlockProperty[]{}),
    WATERLILY("minecraft:waterlily", new BlockProperty[]{}),
    NETHER_BRICK("minecraft:nether_brick", new BlockProperty[]{}),
    NETHER_BRICK_FENCE("minecraft:nether_brick_fence", new BlockProperty[]{}),
    NETHER_BRICK_STAIRS("minecraft:nether_brick_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    NETHER_WART("minecraft:nether_wart", new BlockProperty[]{BlockProperty.AGE}),
    ENCHANTING_TABLE("minecraft:enchanting_table", new BlockProperty[]{}),
    BREWING_STAND("minecraft:brewing_stand", new BlockProperty[]{BlockProperty.BREWING_STAND_SLOT_A_BIT, BlockProperty.BREWING_STAND_SLOT_B_BIT, BlockProperty.BREWING_STAND_SLOT_C_BIT}),
    CAULDRON("minecraft:cauldron", new BlockProperty[]{BlockProperty.CAULDRON_LIQUID, BlockProperty.FILL_LEVEL}),
    END_PORTAL("minecraft:end_portal", new BlockProperty[]{}),
    END_PORTAL_FRAME("minecraft:end_portal_frame", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.END_PORTAL_EYE_BIT}),
    END_STONE("minecraft:end_stone", new BlockProperty[]{}),
    DRAGON_EGG("minecraft:dragon_egg", new BlockProperty[]{}),
    REDSTONE_LAMP("minecraft:redstone_lamp", new BlockProperty[]{}),
    LIT_REDSTONE_LAMP("minecraft:lit_redstone_lamp", new BlockProperty[]{}),
    DROPPER("minecraft:dropper", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.TRIGGERED_BIT}),
    ACTIVATOR_RAIL("minecraft:activator_rail", new BlockProperty[]{BlockProperty.RAIL_DIRECTION, BlockProperty.RAIL_DATA_BIT}),
    COCOA("minecraft:cocoa", new BlockProperty[]{}),
    SANDSTONE_STAIRS("minecraft:sandstone_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    EMERALD_ORE("minecraft:emerald_ore", new BlockProperty[]{}),
    ENDER_CHEST("minecraft:ender_chest", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    TRIPWIRE_HOOK("minecraft:tripwire_hook", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.ATTACHED_BIT, BlockProperty.POWERED_BIT}),
    TRIPWIRE("minecraft:tripWire", new BlockProperty[]{BlockProperty.ATTACHED_BIT, BlockProperty.DISARMED_BIT, BlockProperty.POWERED_BIT, BlockProperty.SUSPENDED_BIT}),
    EMERALD_BLOCK("minecraft:emerald_block", new BlockProperty[]{}),
    SPRUCE_STAIRS("minecraft:spruce_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    BIRCH_STAIRS("minecraft:birch_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    JUNGLE_STAIRS("minecraft:jungle_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    BEACON("minecraft:beacon", new BlockProperty[]{}),
    COBBLESTONE_WALL("minecraft:cobblestone_wall", new BlockProperty[]{BlockProperty.WALL_BLOCK_TYPE}),
    FLOWER_POT("minecraft:flower_pot", new BlockProperty[]{BlockProperty.UPDATE_BIT}),
    CARROTS("minecraft:carrots", new BlockProperty[]{BlockProperty.GROWTH}),
    POTATOES("minecraft:potatoes", new BlockProperty[]{BlockProperty.GROWTH}),
    WOODEN_BUTTON("minecraft:wooden_button", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.BUTTON_PRESSED_BIT}),
    SKULL("minecraft:skull", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.NO_DROP_BIT}),
    ANVIL("minecraft:anvil", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.DAMAGE}),
    TRAPPED_CHEST("minecraft:trapped_chest", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    LIGHT_WEIGHTED_PRESSURE_PLATE("minecraft:light_weighted_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    HEAVY_WEIGHTED_PRESSURE_PLATE("minecraft:heavy_weighted_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    UNPOWERED_COMPARATOR("minecraft:unpowered_comparator", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OUTPUT_LIT_BIT, BlockProperty.OUTPUT_SUBTRACT_BIT}),
    POWERED_COMPARATOR("minecraft:powered_comparator", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OUTPUT_LIT_BIT, BlockProperty.OUTPUT_SUBTRACT_BIT}),
    DAYLIGHT_DETECTOR("minecraft:daylight_detector", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    REDSTONE_BLOCK("minecraft:redstone_block", new BlockProperty[]{}),
    QUARTZ_ORE("minecraft:quartz_ore", new BlockProperty[]{}),
    HOPPER("minecraft:hopper", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.TOGGLE_BIT}),
    QUARTZ_BLOCK("minecraft:quartz_block", new BlockProperty[]{BlockProperty.CHISEL_TYPE, BlockProperty.PILLAR_AXIS}),
    QUARTZ_STAIRS("minecraft:quartz_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    DOUBLE_WOODEN_SLAB("minecraft:double_wooden_slab", new BlockProperty[]{BlockProperty.WOOD_TYPE, BlockProperty.TOP_SLOT_BIT}),
    WOODEN_SLAB("minecraft:wooden_slab", new BlockProperty[]{BlockProperty.WOOD_TYPE, BlockProperty.TOP_SLOT_BIT}),
    STAINED_HARDENED_CLAY("minecraft:stained_hardened_clay", new BlockProperty[]{BlockProperty.COLOR}),
    STAINED_GLASS_PANE("minecraft:stained_glass_pane", new BlockProperty[]{BlockProperty.COLOR}),
    LEAVES2("minecraft:leaves2", new BlockProperty[]{BlockProperty.NEW_LEAF_TYPE, BlockProperty.PERSISTENT_BIT, BlockProperty.UPDATE_BIT}),
    LOG2("minecraft:log2", new BlockProperty[]{BlockProperty.NEW_LOG_TYPE, BlockProperty.PILLAR_AXIS}),
    ACACIA_STAIRS("minecraft:acacia_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    DARK_OAK_STAIRS("minecraft:dark_oak_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    SLIME("minecraft:slime", new BlockProperty[]{}),
    IRON_TRAPDOOR("minecraft:iron_trapdoor", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OPEN_BIT, BlockProperty.UPSIDE_DOWN_BIT}),
    PRISMARINE("minecraft:prismarine", new BlockProperty[]{BlockProperty.PRISMARINE_BLOCK_TYPE}),
    SEALANTERN("minecraft:seaLantern", new BlockProperty[]{}),
    HAY_BLOCK("minecraft:hay_block", new BlockProperty[]{BlockProperty.DEPRECATED, BlockProperty.PILLAR_AXIS}),
    CARPET("minecraft:carpet", new BlockProperty[]{BlockProperty.COLOR}),
    HARDENED_CLAY("minecraft:hardened_clay", new BlockProperty[]{}),
    COAL_BLOCK("minecraft:coal_block", new BlockProperty[]{}),
    PACKED_ICE("minecraft:packed_ice", new BlockProperty[]{}),
    DOUBLE_PLANT("minecraft:double_plant", new BlockProperty[]{BlockProperty.DOUBLE_PLANT_TYPE, BlockProperty.UPPER_BLOCK_BIT}),
    BANNER("minecraft:banner", new BlockProperty[]{}),
    DAYLIGHT_DETECTOR_INVERTED("minecraft:daylight_detector_inverted", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    RED_SANDSTONE("minecraft:red_sandstone", new BlockProperty[]{BlockProperty.SAND_STONE_TYPE}),
    RED_SANDSTONE_STAIRS("minecraft:red_sandstone_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    DOUBLE_STONE_SLAB2("minecraft:double_stone_slab2", new BlockProperty[]{BlockProperty.STONE_SLAB_TYPE_2, BlockProperty.TOP_SLOT_BIT}),
    STONE_SLAB2("minecraft:stone_slab2", new BlockProperty[]{BlockProperty.STONE_SLAB_TYPE_2, BlockProperty.TOP_SLOT_BIT}),
    SPRUCE_FENCE_GATE("minecraft:spruce_fence_gate", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.IN_WALL_BIT, BlockProperty.OPEN_BIT}),
    BIRCH_FENCE_GATE("minecraft:birch_fence_gate", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.IN_WALL_BIT, BlockProperty.OPEN_BIT}),
    JUNGLE_FENCE_GATE("minecraft:jungle_fence_gate", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.IN_WALL_BIT, BlockProperty.OPEN_BIT}),
    DARK_OAK_FENCE_GATE("minecraft:dark_oak_fence_gate", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.IN_WALL_BIT, BlockProperty.OPEN_BIT}),
    ACACIA_FENCE_GATE("minecraft:acacia_fence_gate", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.IN_WALL_BIT, BlockProperty.OPEN_BIT}),
    REPEATING_COMMAND_BLOCK("minecraft:repeating_command_block", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.CONDITIONAL_BIT}),
    CHAIN_COMMAND_BLOCK("minecraft:chain_command_block", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.CONDITIONAL_BIT}),
    HARD_GLASS_PANE("minecraft:hard_glass_pane", new BlockProperty[]{}),
    HARD_STAINED_GLASS_PANE("minecraft:hard_stained_glass_pane", new BlockProperty[]{BlockProperty.COLOR}),
    CHEMICAL_HEAT("minecraft:chemical_heat", new BlockProperty[]{}),
    SPRUCE_DOOR("minecraft:spruce_door", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.DOOR_HINGE_BIT, BlockProperty.OPEN_BIT, BlockProperty.UPPER_BLOCK_BIT}),
    BIRCH_DOOR("minecraft:birch_door", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.DOOR_HINGE_BIT, BlockProperty.OPEN_BIT, BlockProperty.UPPER_BLOCK_BIT}),
    JUNGLE_DOOR("minecraft:jungle_door", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.DOOR_HINGE_BIT, BlockProperty.OPEN_BIT, BlockProperty.UPPER_BLOCK_BIT}),
    ACACIA_DOOR("minecraft:acacia_door", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.DOOR_HINGE_BIT, BlockProperty.OPEN_BIT, BlockProperty.UPPER_BLOCK_BIT}),
    DARK_OAK_DOOR("minecraft:dark_oak_door", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.DOOR_HINGE_BIT, BlockProperty.OPEN_BIT, BlockProperty.UPPER_BLOCK_BIT}),
    GRASS_PATH("minecraft:grass_path", new BlockProperty[]{}),
    FRAME("minecraft:frame", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.ITEM_FRAME_MAP_BIT}),
    CHORUS_FLOWER("minecraft:chorus_flower", new BlockProperty[]{BlockProperty.AGE}),
    PURPUR_BLOCK("minecraft:purpur_block", new BlockProperty[]{BlockProperty.CHISEL_TYPE, BlockProperty.PILLAR_AXIS}),
    PURPUR_STAIRS("minecraft:purpur_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    SHULKER_BOX("minecraft:shulker_box", new BlockProperty[]{BlockProperty.COLOR}),
    END_BRICKS("minecraft:end_bricks", new BlockProperty[]{}),
    END_ROD("minecraft:end_rod", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    END_GATEWAY("minecraft:end_gateway", new BlockProperty[]{}),
    B_210("minecraft:210", new BlockProperty[]{}),
    B_211("minecraft:211", new BlockProperty[]{}),
    B_212("minecraft:212", new BlockProperty[]{}),
    MAGMA("minecraft:magma", new BlockProperty[]{}),
    NETHER_WART_BLOCK("minecraft:nether_wart_block", new BlockProperty[]{}),
    RED_NETHER_BRICK("minecraft:red_nether_brick", new BlockProperty[]{}),
    BONE_BLOCK("minecraft:bone_block", new BlockProperty[]{BlockProperty.DEPRECATED, BlockProperty.PILLAR_AXIS}),
    PURPLE_GLAZED_TERRACOTTA("minecraft:purple_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    WHITE_GLAZED_TERRACOTTA("minecraft:white_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    ORANGE_GLAZED_TERRACOTTA("minecraft:orange_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    MAGENTA_GLAZED_TERRACOTTA("minecraft:magenta_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    LIGHT_BLUE_GLAZED_TERRACOTTA("minecraft:light_blue_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    YELLOW_GLAZED_TERRACOTTA("minecraft:yellow_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    LIME_GLAZED_TERRACOTTA("minecraft:lime_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    PINK_GLAZED_TERRACOTTA("minecraft:pink_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    GRAY_GLAZED_TERRACOTTA("minecraft:gray_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    SILVER_GLAZED_TERRACOTTA("minecraft:silver_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    CYAN_GLAZED_TERRACOTTA("minecraft:cyan_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    B_230("minecraft:230", new BlockProperty[]{}),
    BLUE_GLAZED_TERRACOTTA("minecraft:blue_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    BROWN_GLAZED_TERRACOTTA("minecraft:brown_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    GREEN_GLAZED_TERRACOTTA("minecraft:green_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    RED_GLAZED_TERRACOTTA("minecraft:red_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    BLACK_GLAZED_TERRACOTTA("minecraft:black_glazed_terracotta", new BlockProperty[]{BlockProperty.FACING_DIRECTION}),
    CONCRETE("minecraft:concrete", new BlockProperty[]{BlockProperty.COLOR}),
    CONCRETEPOWDER("minecraft:concretePowder", new BlockProperty[]{BlockProperty.COLOR}),
    CHEMISTRY_TABLE("minecraft:chemistry_table", new BlockProperty[]{BlockProperty.CHEMISTRY_TABLE_TYPE, BlockProperty.DIRECTION}),
    UNDERWATER_TORCH("minecraft:underwater_torch", new BlockProperty[]{BlockProperty.TORCH_FACING_DIRECTION}),
    CHORUS_PLANT("minecraft:chorus_plant", new BlockProperty[]{}),
    STAINED_GLASS("minecraft:stained_glass", new BlockProperty[]{BlockProperty.COLOR}),
    B_242("minecraft:242", new BlockProperty[]{}),
    PODZOL("minecraft:podzol", new BlockProperty[]{}),
    BEETROOT("minecraft:beetroot", new BlockProperty[]{BlockProperty.GROWTH}),
    STONECUTTER("minecraft:stonecutter", new BlockProperty[]{}),
    GLOWINGOBSIDIAN("minecraft:glowingobsidian", new BlockProperty[]{}),
    NETHERREACTOR("minecraft:netherreactor", new BlockProperty[]{}),
    INFO_UPDATE("minecraft:info_update", new BlockProperty[]{}),
    INFO_UPDATE2("minecraft:info_update2", new BlockProperty[]{}),
    MOVINGBLOCK("minecraft:movingBlock", new BlockProperty[]{}),
    OBSERVER("minecraft:observer", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.POWERED_BIT}),
    STRUCTURE_BLOCK("minecraft:structure_block", new BlockProperty[]{BlockProperty.STRUCTURE_BLOCK_TYPE}),
    HARD_GLASS("minecraft:hard_glass", new BlockProperty[]{}),
    HARD_STAINED_GLASS("minecraft:hard_stained_glass", new BlockProperty[]{BlockProperty.COLOR}),
    RESERVED6("minecraft:reserved6", new BlockProperty[]{}),
    B_256("minecraft:256", new BlockProperty[]{}),
    PRISMARINE_STAIRS("minecraft:prismarine_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    DARK_PRISMARINE_STAIRS("minecraft:dark_prismarine_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    PRISMARINE_BRICKS_STAIRS("minecraft:prismarine_bricks_stairs", new BlockProperty[]{BlockProperty.WEIRDO_DIRECTION, BlockProperty.UPSIDE_DOWN_BIT}),
    STRIPPED_SPRUCE_LOG("minecraft:stripped_spruce_log", new BlockProperty[]{BlockProperty.PILLAR_AXIS}),
    STRIPPED_BIRCH_LOG("minecraft:stripped_birch_log", new BlockProperty[]{BlockProperty.PILLAR_AXIS}),
    STRIPPED_JUNGLE_LOG("minecraft:stripped_jungle_log", new BlockProperty[]{BlockProperty.PILLAR_AXIS}),
    STRIPPED_ACACIA_LOG("minecraft:stripped_acacia_log", new BlockProperty[]{BlockProperty.PILLAR_AXIS}),
    STRIPPED_DARK_OAK_LOG("minecraft:stripped_dark_oak_log", new BlockProperty[]{BlockProperty.PILLAR_AXIS}),
    STRIPPED_OAK_LOG("minecraft:stripped_oak_log", new BlockProperty[]{BlockProperty.PILLAR_AXIS}),
    BLUE_ICE("minecraft:blue_ice", new BlockProperty[]{}),
    SEAGRASS("minecraft:seagrass", new BlockProperty[]{BlockProperty.SEA_GRASS_TYPE}),
    CORAL("minecraft:coral", new BlockProperty[]{BlockProperty.CORAL_COLOR, BlockProperty.DEAD_BIT}),
    CORAL_BLOCK("minecraft:coral_block", new BlockProperty[]{BlockProperty.CORAL_COLOR, BlockProperty.DEAD_BIT}),
    CORAL_FAN("minecraft:coral_fan", new BlockProperty[]{BlockProperty.CORAL_COLOR, BlockProperty.CORAL_FAN_DIRECTION}),
    CORAL_FAN_DEAD("minecraft:coral_fan_dead", new BlockProperty[]{BlockProperty.CORAL_COLOR, BlockProperty.CORAL_FAN_DIRECTION}),
    CORAL_FAN_HANG("minecraft:coral_fan_hang", new BlockProperty[]{BlockProperty.CORAL_HANG_TYPE_BIT, BlockProperty.CORAL_DIRECTION, BlockProperty.DEAD_BIT}),
    CORAL_FAN_HANG2("minecraft:coral_fan_hang2", new BlockProperty[]{BlockProperty.CORAL_HANG_TYPE_BIT, BlockProperty.CORAL_DIRECTION, BlockProperty.DEAD_BIT}),
    CORAL_FAN_HANG3("minecraft:coral_fan_hang3", new BlockProperty[]{BlockProperty.CORAL_HANG_TYPE_BIT, BlockProperty.CORAL_DIRECTION, BlockProperty.DEAD_BIT}),
    KELP("minecraft:kelp", new BlockProperty[]{BlockProperty.KELP_AGE}),
    DRIED_KELP_BLOCK("minecraft:dried_kelp_block", new BlockProperty[]{}),
    ACACIA_BUTTON("minecraft:acacia_button", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.BUTTON_PRESSED_BIT}),
    BIRCH_BUTTON("minecraft:birch_button", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.BUTTON_PRESSED_BIT}),
    DARK_OAK_BUTTON("minecraft:dark_oak_button", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.BUTTON_PRESSED_BIT}),
    JUNGLE_BUTTON("minecraft:jungle_button", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.BUTTON_PRESSED_BIT}),
    SPRUCE_BUTTON("minecraft:spruce_button", new BlockProperty[]{BlockProperty.FACING_DIRECTION, BlockProperty.BUTTON_PRESSED_BIT}),
    ACACIA_TRAPDOOR("minecraft:acacia_trapdoor", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OPEN_BIT, BlockProperty.UPSIDE_DOWN_BIT}),
    BIRCH_TRAPDOOR("minecraft:birch_trapdoor", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OPEN_BIT, BlockProperty.UPSIDE_DOWN_BIT}),
    DARK_OAK_TRAPDOOR("minecraft:dark_oak_trapdoor", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OPEN_BIT, BlockProperty.UPSIDE_DOWN_BIT}),
    JUNGLE_TRAPDOOR("minecraft:jungle_trapdoor", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OPEN_BIT, BlockProperty.UPSIDE_DOWN_BIT}),
    SPRUCE_TRAPDOOR("minecraft:spruce_trapdoor", new BlockProperty[]{BlockProperty.DIRECTION, BlockProperty.OPEN_BIT, BlockProperty.UPSIDE_DOWN_BIT}),
    ACACIA_PRESSURE_PLATE("minecraft:acacia_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    BIRCH_PRESSURE_PLATE("minecraft:birch_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    DARK_OAK_PRESSURE_PLATE("minecraft:dark_oak_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    JUNGLE_PRESSURE_PLATE("minecraft:jungle_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    SPRUCE_PRESSURE_PLATE("minecraft:spruce_pressure_plate", new BlockProperty[]{BlockProperty.REDSTONE_SIGNAL}),
    CARVED_PUMPKIN("minecraft:carved_pumpkin", new BlockProperty[]{BlockProperty.DIRECTION}),
    SEA_PICKLE("minecraft:sea_pickle", new BlockProperty[]{BlockProperty.CLUSTER_COUNT, BlockProperty.DEAD_BIT}),
    UNKNOWN("blocktopograph:unknown", new BlockProperty[0]);

    private static final Map<String, BlockType> blockTypes = new HashMap<>();

    private final String name;

    private final BlockProperty[] knownProperties;

    static {
        for (var block : BlockType.values()) blockTypes.put(block.name, block);
    }

    BlockType(String name, BlockProperty[] knownProperties) {
        this.name = name;
        this.knownProperties = knownProperties;
    }

    @Nullable
    public static BlockType get(String name) {
        return blockTypes.get(name);
    }

    public String getName() {
        return name;
    }

    public BlockProperty[] getKnownProperties() {
        return knownProperties;
    }
}
